services:
  rstudio:
    image: emanuelespiritowork/pristar-geospec:0.3
    container_name: pristar-geospec
    ports: ["${PORT_rstudio}:8787"]
    environment:
      DISABLE_AUTH: true
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPUS}
    volumes:
      - ${IMAGES_PATH}:/space
      - ${CONFIG_PATH}:/config_folder
    command: /init

  isofit:
    image: lorenzopari/isofit-api:latest
    container_name: PRISTAR_isofit
    ports:
      - "${PORT_isofit}:8000"
    volumes:
      - ${IMAGES_PATH}:/space
      - ${CONFIG_PATH}:/config_folder
      
  arosics:
    image: lorenzopari/arosics:1.13.2
    container_name: PRISTAR_arosics
    ports:
      - "${PORT_arosics}:8000"
    volumes:
      - ${IMAGES_PATH}:/space
      - ${CONFIG_PATH}:/config_folder      