services:
  rstudio:
    image: emanuelespiritowork/pristar-geospec:0.3
    container_name: pristar-geospec
    ports: ["8787:8787"]
    environment:
      DISABLE_AUTH: true
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPUS}
    volumes:
      - ${IMAGES_PATH}:/space
      - ${CONFIG_PATH}:/config_folder
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c "apt-get update && apt-get install -y docker.io && chmod 666 /var/run/docker.sock && /init"

  isofit:
    image: jammont/isofit:latest
    container_name: PRISTAR_isofit
    ports:
      - "8001:8000"
    volumes:
      - ${IMAGES_PATH}:/space
      - ${CONFIG_PATH}:/config_folder
      
  arosics:
    image: jammont/isofit:latest
    container_name: PRISTAR_arosics
    ports:
      - "8002:8000"
    volumes:
      - ${IMAGES_PATH}:/space
      - ${CONFIG_PATH}:/config_folder      