services:
  rstudio:
    image: lorenzopari/test_pristar:0.4
    container_name: pristar-geospec
    ports: ["${PORT_rstudio}:8787"]
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT}
    environment:
      DISABLE_AUTH: true
      ROOT: true
    volumes:
      - ${IMAGES_PATH}:/space
      - ${CONFIG_PATH}:/config_folder
    command: /init
    networks: [PRISTAR_net]

  isofit:
    image: lorenzopari/isofit-api:4.0.0
    container_name: PRISTAR_isofit
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT}
    volumes:
      - ${IMAGES_PATH}:/space
      - ${CONFIG_PATH}:/config_folder
    networks: [PRISTAR_net]
      
  arosics:
    image: lorenzopari/arosics:1.13.2
    container_name: PRISTAR_arosics
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT}
    volumes:
      - ${IMAGES_PATH}:/space
      - ${CONFIG_PATH}:/config_folder 
    networks: [PRISTAR_net]    
      
      
networks:
  PRISTAR_net: