services:
  rstudio:
    image: lorenzopari/test_pristar:0.4
    container_name: pristar-geospec
    ports: ["${PORT_rstudio}:8787"]
    environment:
      DISABLE_AUTH: true
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPUS}
    volumes:
      - ${IMAGES_PATH}:/space
      - ${CONFIG_PATH}:/config_folder
    command: /init
    networks: [PRISTAR_net]

  isofit:
    image: lorenzopari/isofit-api:latest
    container_name: PRISTAR_isofit
    volumes:
      - ${IMAGES_PATH}:/space
      - ${CONFIG_PATH}:/config_folder
    networks: [PRISTAR_net]
      
  arosics:
    image: lorenzopari/arosics:1.13.2
    container_name: PRISTAR_arosics
    volumes:
      - ${IMAGES_PATH}:/space
      - ${CONFIG_PATH}:/config_folder 
    networks: [PRISTAR_net]    
      
      
networks:
  PRISTAR_net: